#!/bin/bash
# 
# xmonad startup script. Intended to be run from an xsession configuration
# to run xmonad and some associated programs.
# 
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# KLUDGES AND WORKAROUNDS
#

# Clear xmonad.state before starting xmonad -- otherwise this causes weird
# issues, especially when going between single screen and multi-screen
rm -f ~/.xmonad/xmonad.state

#
# GENERAL INITIALIZATION
#

# Identify the home of our gtkrc file, important for setting styles of 
# gtk-based applications
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# Load X resources (fixes some font issues)
xrdb -merge .Xresources

# Start compositing to support transparency. You can omit this
# if you prefer not to use any transparency, but it is likely to cause
# ugly black fringing with some programs such as synapse that expect
# transparency support.
xcompmgr -n &

#
# SCREEN CONFIGURATION
#

# Trayer
trayer \
  --monitor "primary" \
  --edge top \
  --align right \
  --widthtype percent \
  --padding 10 \
  --width 10 \
  --height 19 \
  --transparent true \
  --tint 0x000000 \
  --expand true \
  --alpha 55 &

# Activate primary screen 
xrandr --output DP-2 --auto --secondary
xrandr --output DP-4 --auto --primary

# xrandr --output DP-2 --right-of DP-4

#
# LOAD SCREEN BACKGROUNDS
#

# To set your backgrounds, run nitrogren /path/to/images
nitrogen --restore &

#
# STARTUP ICON TRAY
#
# Run the gnome-keyring-daemon to avoid issues you otherwise may encounter
# when using gnome applications which expect access to the keyring, such
# as Empathy. This prevents prompts you may otherwise get for invalid
# certificates and the like.
gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

# Remap caps lock to left control. This is not strictly speaking
# xmonad related, but it's handy if you're a vim user.
# setxkbmap -option 'ctrl:nocaps'

# Change the default X cursor away from the "X"
xsetroot -cursor_name left_ptr


setxkbmap us

# Now, finally, start xmonad
exec xmonad

